server:
  port: 10003

spring:
  application:
    name: outsourcing_system_hangzhou

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.61.3:3306/customer_hangzhou?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    producer:
      acks: -1
    bootstrap-servers: 192.168.61.3:9092, 192.168.61.3:9092