server:
  port: 9003
    
management:
  endpoints:
    web:
      exposure:
        include: "*"  

spring:
  application:
    name: im-server

logging:
    level:
      com.ocbc.project.im.router: INFO

      
